### ISSUE TITLE
Refactor simulation workflow functions

### ISSUE THREAD

**Issue by lunafazio** [bmfazio/lunafuns#1]
## Main idea
Centralize workflow with new "gateway" function `bdlvm`

### Design goals
- Can use to directly run a single fit given a model formula, dataframe and priors (basically enhanced `brm`)
- Can use to simulate datasets given a model formula and priors (for random parameter drawing, fixed params as particular case). Likely to use `SBC` machinery internally.
- Can use to fit a given model formula and priors over a set of simulated datasets. Again in line with established `SBC` workflow.

### Additional considerations
- **IMPORTANT:** Play nicely with `targets` by making any call to SBC data generation/model fitting as "clean" as possible for any given use in order to avoid unnecessary re-runs. Most likely by generating intermediate S3 object that is handled through use case-specific methods.
- To simplify iteration over different conditions, allow any given argument to be specified as list which is then handled via either a "paired" or "crossed" method with the rest of arguments. Default iteration mode should be "none" to avoid accidents.
- To avoid memory issues due to huge objects, iteration mode should return a dataframe(?) with auto-generated simulation id (probably based on arguments that will be iterated over) and individual ready-made function calls. Should play nicely with static branching via `tarchetypes`.

### Other random notes

```
> desired input format
bdlvm(formula [bf+lv], data [dataframe/tibble], priors, stanvars,  backend + backend config], [modify stan (func)], summary func (kills draws))
> desired output
brmsfit(?)

bdlvm(formula, dataset info (size, parameters (priors), sim info (iters))
- run SBC on generated datasets using a given formula+prior
same as "single model" except data argument is the datasets object!
> desired output
SBC results object but give option to "collapse" results via some summary func

[EXPERIMENTAL] template/default arg creation:
for easy reuse of short calls when running sims with repetitive patterns,
an argument that returns the function with defaults set by the user specified
arguments and leaves all the rest free

```

**Comment by bmfazio** [comment]
Testing if R codeblocks render nicely

``` r
# Setup
library(lunafuns)
```

**Comment by lunafazio** [comment]
Implemented as separate library https://github.com/bmfazio/bdlvm
